name: Build and publish Azure Function (Docker)

on:
  push:
    branches: [ main ]
    paths:
    - "FunctionAppContainerReleaseStrategy/**"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: serverlessday2021.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Calculate Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: 'Build Docker Image'
      shell: bash
      run: docker build . -t serverlessday2021.azurecr.io/azurefunctiondemo:${{ steps.gitversion.outputs.sha }}
      working-directory: FunctionAppContainerReleaseStrategy
        
    - name: 'Push Docker Image'
      shell: bash
      run: docker push serverlessday2021.azurecr.io/azurefunctiondemo:${{ steps.gitversion.outputs.sha }}

    - name: 'Deploy'
      uses: Azure/functions-container-action@v1
      id: deploy
      with:
        app-name: serverlessday2021oncontainer
        image: serverlessday2021.azurecr.io/azurefunctiondemo:${{ steps.gitversion.outputs.sha }}

    - name: 'Check function is running'
      shell: bash
      run: curl -s "${{ steps.deploy.outputs.app-url }}/api/Hello?name=GitHub"
